always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
import_to_using = true
normalize_line_endings = "unix"
separate_kwargs_with_semicolon = true
whitespace_in_kwargs = false
short_to_long_function_def = true
long_to_short_function_def = true
conditional_to_if = true
trailing_comma = true
